### ISSUE TITLE
Vagrant up failes with error

### ISSUE THREAD

**Issue by amitkrout** [projectatomic/adb-tests#45]
This line ```self.log.info(child.after)`` is throwing error. Need to debug it more

**Comment by hferentschik** [comment]
What is the error?

**Comment by amitkrout** [comment]
Environment : 

```
System Version: OS X 10.11.6 (15G31)
Kernel Version: Darwin 15.6.0
Avocado 36.0lts
```

Steps to reproduce 

```
1. Download latest CDK + virtualbox provider on mac 
2. Clone  "https://github.com/projectatomic/adb-tests" and modify the config.yaml 
    vagrant_VAGRANTFILE_DIR : ".../cdk/components/rhel/rhel-ose"
     vagrant_PROVIDER : "virtualbox"
     vagrant_RHN_USERNAME : "usename"
     vagrant_RHN_PASSWORD : "password"
     openshift_lib_MODULE : ".../adb-tests/cdk-testsuite/libraries/openshift/openshift.py"
     openshift_util_MODULE : ".../adb-tests/cdk-testsuite/utils/openshiftUtils.py"
3. Go to the directory "/adb-tests/cdk-testsuite/tests" and execute the command 
    "avocado run vagrant_sanity.py -m ../config/config.yaml"
```

ERROR : 

```
2016-10-26 15:33:26,871 stacktrace       L0036 ERROR| 
2016-10-26 15:33:26,871 stacktrace       L0039 ERROR| Reproduced traceback from: /Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/test.py:435
2016-10-26 15:33:26,874 stacktrace       L0042 ERROR| Traceback (most recent call last):
2016-10-26 15:33:26,874 stacktrace       L0042 ERROR|   File "/Users/cdkqe/NightlyBuild/adb-tests/cdk-testsuite/tests/vagrant_sanity.py", line 54, in test_vagrant_up
2016-10-26 15:33:26,874 stacktrace       L0042 ERROR|     child.sendline (self.sudo_PASSWORD)
2016-10-26 15:33:26,874 stacktrace       L0042 ERROR|   File "/Library/Python/2.7/site-packages/pexpect/pty_spawn.py", line 535, in sendline
2016-10-26 15:33:26,875 stacktrace       L0042 ERROR|     return self.send(s + self.linesep)
2016-10-26 15:33:26,875 stacktrace       L0042 ERROR|   File "/Library/Python/2.7/site-packages/pexpect/pty_spawn.py", line 526, in send
2016-10-26 15:33:26,875 stacktrace       L0042 ERROR|     return os.write(self.child_fd, b)
2016-10-26 15:33:26,875 stacktrace       L0042 ERROR| OSError: [Errno 5] Input/output error
2016-10-26 15:33:26,875 stacktrace       L0043 ERROR| 
2016-10-26 15:33:26,978 test             L0550 ERROR| Traceback (most recent call last):

2016-10-26 15:33:26,978 test             L0550 ERROR|   File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/test.py", line 490, in _run_avocado
    raise test_exception

2016-10-26 15:33:26,979 test             L0550 ERROR| OSError: [Errno 5] Input/output error

2016-10-26 15:33:26,979 test             L0567 ERROR| ERROR 1-vagrant_sanity.py:VagrantSanity.test_vagrant_up -> OSError: [Errno 5] Input/output error
```
